name: ci

on: [push, pull_request]

jobs:
  test-php:
    name: PHP ${{ matrix.php }} TDEngine ${{ matrix.tdengine }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, '8.0', 8.1]
        tdengine: [2.0.22.0]
    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}
      TDENGINE_VERSION: ${{ matrix.tdengine }}
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          cd .github
          docker-compose up -d
          docker exec php composer update
      - name: test
        run: docker exec php composer test

  test-tdengine:
    name: PHP ${{ matrix.php }} TDEngine ${{ matrix.tdengine }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        tdengine: [2.2.2.0]
    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}
      TDENGINE_VERSION: ${{ matrix.tdengine }}
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          cd .github
          docker-compose up -d
          docker exec php composer update
      - name: test
        run: docker exec php composer test
